### ISSUE TITLE
Create navbar

### ISSUE THREAD

**Issue by Lordpluha** [NovaDevelopersCo/nova-learn-crm-web#2]
### Todo
- [x] Create Navbar widget
- [x] Add mobile version
- [x] Try to create your custom table version
- [x] Create links to pages (work with #4)
### Examples

![Image](https://github.com/NovaDevelopersCo/nova-learn-crm-web/assets/109725756/3c9ac9e2-11cd-40f7-9bfb-5250b06ae979)

![Image](https://github.com/NovaDevelopersCo/nova-learn-crm-web/assets/109725756/79293d67-1c16-496a-9eff-ccd8160ff3d0)
